 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/check_items", type: :request do
  
  # CheckItem. As you add validations to CheckItem, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      CheckItem.create! valid_attributes
      get check_items_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      check_item = CheckItem.create! valid_attributes
      get check_item_url(check_item)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_check_item_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      check_item = CheckItem.create! valid_attributes
      get edit_check_item_url(check_item)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new CheckItem" do
        expect {
          post check_items_url, params: { check_item: valid_attributes }
        }.to change(CheckItem, :count).by(1)
      end

      it "redirects to the created check_item" do
        post check_items_url, params: { check_item: valid_attributes }
        expect(response).to redirect_to(check_item_url(CheckItem.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new CheckItem" do
        expect {
          post check_items_url, params: { check_item: invalid_attributes }
        }.to change(CheckItem, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post check_items_url, params: { check_item: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested check_item" do
        check_item = CheckItem.create! valid_attributes
        patch check_item_url(check_item), params: { check_item: new_attributes }
        check_item.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the check_item" do
        check_item = CheckItem.create! valid_attributes
        patch check_item_url(check_item), params: { check_item: new_attributes }
        check_item.reload
        expect(response).to redirect_to(check_item_url(check_item))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        check_item = CheckItem.create! valid_attributes
        patch check_item_url(check_item), params: { check_item: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested check_item" do
      check_item = CheckItem.create! valid_attributes
      expect {
        delete check_item_url(check_item)
      }.to change(CheckItem, :count).by(-1)
    end

    it "redirects to the check_items list" do
      check_item = CheckItem.create! valid_attributes
      delete check_item_url(check_item)
      expect(response).to redirect_to(check_items_url)
    end
  end
end
